version: "3.8"

services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - dbdata:/var/lib/postgresql/data

    app:
        container_name: app
        build: .
        depends_on:
            - "postgres"

volumes:
    dbdata:
